# Mapped classes for the HTML forms generated by WTForms

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, URL


class CrawlingRuleForm(FlaskForm):
    address = StringField('Web page address', validators=[DataRequired(), URL()])
    selector = StringField('CSS selector', validators=[DataRequired()])
    description = StringField('Rule description')
    crawlPeriod = IntegerField('Crawling every', validators=[DataRequired()])
    crawlPeriodUnitType = SelectField('Time unit', choices=[('hours', 'hours'), ('minutes', 'minutes')])
    submit = SubmitField('Add crawling rule')

    def validate(self):
        if not FlaskForm.validate(self):
            return False

        if self.crawlPeriodUnitType.data == 'hours' and (self.crawlPeriod.data < 1 or self.crawlPeriod.data > 24):
            self.crawlPeriod.errors.append("Invalid hours value. Must be in [1, 24]")
            return False
        elif self.crawlPeriodUnitType.data == 'minutes' and (self.crawlPeriod.data < 1 or self.crawlPeriod.data > 90):
            self.crawlPeriod.errors.append("Invalid minutes value. Must be in [1, 90]")
            return False

        return True
